export const TICK = "TICK";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

export const GET_HOME_PHOTOS = "GET_HOME_PHOTOS";
export const GET_HOME_PHOTOS_SUCCED = "GET_HOME_PHOTOS_SUCCED";
export const GET_HOME_PHOTOS_FAIL = "GET_HOME_PHOTOS_FAIL";
export const RESET_HOME_PHOTOS = "RESET_HOME_PHOTOS";

export const GET_TEAM_CONTENT = "GET_TEAM_CONTENT";
export const GET_TEAM_CONTENT_SUCCESS = "GET_TEAM_CONTENT_SUCCESS";
export const GET_TEAM_CONTENT_FAIL = "GET_TEAM_CONTENT_FAIL";

export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS";
export const GET_TEAM_MEMBERS_SUCCESS = "GET_TEAM_MEMBERS_SUCCESS";
export const GET_TEAM_MEMBERS_FAIL = "GET_TEAM_MEMBERS_FAIL";

export const GET_FOOTER_DATA = "GET_FOOTER_DATA";
export const GET_FOOTER_DATA_SUCCED = "GET_FOOTER_DATA_SUCCESS";
export const GET_FOOTER_DATA_FAIL = "GET_FOOTER_DATA_FAIL";

export const GET_IMAGE_DETAILS = "GET_IMAGE_DETAILS";
export const GET_IMAGE_DETAILS_SUCCED = "GET_IMAGE_DETAILS_SUCCED";
export const GET_IMAGE_DETAILS_FAIL = "GET_IMAGE_DETAILS_FAIL";
export const GET_IMAGE_RELATED_SUCCED = "GET_IMAGE_RELATED_SUCCED";
export const GET_IMAGE_RELATED_FAIL = "GET_IMAGE_RELATED_FAIL";

export const GET_SIGNUP = "GET_SIGNUP";
export const POST_SIGNUP = "POST_SIGNUP";

export const OPEN_MODAL_SIGN_UP = "OPEN_MODAL_SIGN_UP";
export const OPEN_MODAL_FORGET_PASWWORD = "OPEN_MODAL_FORGET_PASWWORD";
export const CLOSE_MODAL_SIGN_UP = "CLOSE_MODAL_SIGN_UP";
export const CLOSE_MODAL_FORGET_PASWWORD = "CLOSE_MODAL_FORGET_PASWWORD";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
export const OPEN_MODAL_CHECKOUT = "OPEN_MODAL_CHECKOUT";
export const CLOSE_MODAL_CHECKOUT = "CLOSE_MODAL_CHECKOUT";

export const GET_CATALOG_DETAILS = "GET_CATALOG_DETAILS";
export const GET_CATALOG_DETAILS_SUCCED = "GET_CATALOG_DETAILS_SUCCED";
export const GET_CATALOG_DETAILS_FAIL = "GET_CATALOG_DETALS_FAIL";

export const SHOW_MODAL = "SHOW_MODAL";

export const GET_CMS_DATA = "GET_CMS_DATA";
export const GET_CMS_DATA_SUCCED = "GET_CMS_DATA_SUCCED";
export const GET_CMS_DATA_FAIL = "GET_CMS_DATA_FAIL";

export const GET_DATE_PHOTOS = "GET_DATA_PHOTOS";
export const GET_DATE_PHOTOS_SUCCED = "GET_DATE_PHOTOS_SUCCED";
export const GET_DATE_PHOTOS_FAIL = "GET_DATE_PHOTOS_FAIL";

export const GET_TAG_LOGO = "GET_TAG_LOGO";
export const GET_TAG_LOGO_SUCCED = "GET_TAG_LOGO_SUCCED";
export const GET_TAG_LOGO_FAIL = "GET_TAG_LOGO_FAIL";

export const POST_ALBUM_SEARCH = "POST_ALBUM_SEARCH";
export const POST_ALBUM_SEARCH_SUCCED = "POST_ALBUM_SEARCH_SUCCED";
export const POST_ALBUM_SEARCH_FAIL = "POST_ALBUM_SEARCH_FAIL";

export const POST_USERS_SEARCH = "POST_USERS_SEARCH";
export const POST_USERS_SEARCH_SUCCED = "POST_USERS_SEARCH_SUCCED";
export const POST_USERS_SEARCH_FAIL = "POST_USERS_SEARCH_FAIL";

export const POST_KEYWORDS_SEARCH = "POST_KEYWORDS_SEARCH";
export const POST_KEYWORDS_SEARCH_SUCCED = "POST_KEYWORDS_SEARCH_SUCCED";
export const POST_KEYWORDS_SEARCH_FAIL = "POST_KEYWORDS_SEARCH_FAIL";

export const POST_CATALOG_SEARCH = "POST_CATALOG_SEARCH";
export const POST_CATALOG_SEARCH_SUCCED = "POST_CATALOG_SEARCH_SUCCED";
export const POST_CATALOG_SEARCH_FAIL = "POST_CATALOG_SEARCH_FAIL";

export const GET_ALBUMS_PHOTOS = "GET_ALBUMS_PHOTOS";
export const GET_ALBUMS_PHOTOS_SUCCED = "GET_ALBUMS_PHOTOS_SUCCED";
export const GET_ALBUMS_PHOTOS_FAIL = "GET_ALBUMS_PHOTOS_FAIL";

export const POST_ALBUM_SEARCH_LOAD = "POST_ALBUM_SEARCH_LOAD";
export const POST_ALBUM_SEARCH_LOAD_SUCCED = "POST_ALBUM_SEARCH_LOAD_SUCCED";
export const POST_ALBUM_SEARCH_LOAD_FAIL = "POST_ALBUM_SEARCH_LOAD_FAIL";

export const POST_CATALOG_SEARCH_LOAD = "POST_CATALOG_SEARCH_LOAD";
export const POST_CATALOG_SEARCH_LOAD_SUCCED =
  "POST_CATALOG_SEARCH_LOAD_SUCCED";
export const POST_CATALOG_SEARCH_LOAD_FAIL = "POST_CATALOG_SEARCH_LOAD_FAIL";

export const POST_USERS_SEARCH_LOAD = "POST_USERS_SEARCH_LOAD";
export const POST_USERS_SEARCH_LOAD_SUCCED = "POST_USERS_SEARCH_LOAD_SUCCED";
export const POST_USERS_SEARCH_LOAD_FAIL = "POST_USERS_SEARCH_LOAD_FAIL";

export const POST_COLLECTIONS_SEARCH_LOAD = "POST_COLLECTIONS_SEARCH_LOAD";
export const POST_COLLECTIONS_SEARCH_LOAD_SUCCED =
  "POST_COLLECTIONS_SEARCH_LOAD_SUCCED";
export const POST_COLLECTIONS_SEARCH_LOAD_FAIL = "POST_COLLECTIONS_SEARCH_LOAD";

export const GET_LIST_TAGS = "GET_LIST_TAGS";
export const GET_LIST_TAGS_SUCCED = "GET_LIST_TAGS_SUCCED";
export const GET_LIST_TAGS_FAIL = "GET_LIST_TAGS_FAIL";

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_FAIL = "GET_USER_DETAIL_FAIL";

export const GET_USER_ALBUM = "GET_USER_ALBUM";
export const GET_USER_ALBUM_SUCCESS = "GET_USER_ALBUM_SUCCESS";
export const GET_USER_ALBUM_FAIL = "GET_USER_ALBUM_FAIL";

export const GET_ALBUM_DETAILS = "GET_ALBUM_DETAILS";
export const GET_ALBUM_DETAILS_SUCCED = "GET_ALBUM_DETAILS_SUCCED";
export const GET_ALBUM_DETAILS_FAIL = "GET_ALBUM_DETAILS_FAIL";

export const PAGINATE_ALBUM_DETAILS = "PAGINATE_ALBUM_DETAILS";
export const PAGINATE_ALBUM_DETAILS_SUCCED = "PAGINATE_ALBUM_DETAILS_SUCCED";

export const SAVE_GALLERY_IMAGES = "SAVE_GALLERY_IMAGES";

export const GET_PRICE_ALBUM = "GET_PRICE_ALBUM";
export const SELECT_PRICE = "SELECT_PRICE";

export const OPEN_MODAL_SAVE_COLLETION = "OPEN_MODAL_SAVE_COLLECTION";
export const CLOSE_MODAL_SAVE_COLLECTION = "CLOSE_MODAL_SAVE_COLLECTION";
export const OPEN_MODAL_CHOOSE_SIZE = "OPEN_MODAL_CHOOSE_SIZE";
export const CLOSE_MODAL_CHOOSE_SIZE = "CLOSE_MODAL_CHOOSE_SIZE";
export const OPEN_MODAL_GET_LICENSE = "OPEN_MODAL_GET_LICENSE";
export const CLOSE_MODAL_GET_LICENSE = "CLOSE_MODAL_GET_LICENSE";
export const OPEN_MODAL_GET_EMBED = "OPEN_MODAL_GET_EMBED";
export const CLOSE_MODAL_GET_EMBED = "CLOSE_MODAL_GET_EMBED";

export const GET_LIKE_IMAGE = "GET_LIKE_IMAGE";
export const POST_LIKE_IMAGE = "POST_LIKE_IMAGE";

export const CHECKED_SIZE_PICTURE = "CHECKED_SIZE_PICTURE";
export const GET_CART_LIST = "GET_CART_LIST";
export const GET_CART_LIST_FAIL = "GET_CART_LIST_FAIL";
export const DELETE_CART_ITEM_SUCCED = "DELETE_CART_ITEM_SUCCED";
export const DELETE_CART_ITEM_FAIL = "DELETE_CART_ITEM_FAIL";

export const GET_IP = "GET_IP";
export const GET_IP_SUCCED = "GET_IP_SUCCED";
export const GET_IP_FAILD = "GET_IP_FAILD";

export const POST_CART_SUCCEED = "POST_CART_SUCCEED";
export const POST_SELLER = "POST_SELLER";
export const SERVER_SET_COOKIE = "SERVER_SET_COOKIE";
export const CLIENT_REMOVE_COOKIE = "CLIENT_REMOVE_COOKIE";

export const ADD_ALBUM_COLLECTION = "ADD_ALBUM_COLLECTION";
export const ADD_ALBUM_COLLECTION_SUCCED = "ADD_ALBUM_COLLECTION_SUCCED";
export const ADD_ALBUM_COLLECTION_FAILD = "ADD_ALBUM_COLLECTION_FAILD";

export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_COLLECTIONS_SUCCED = "GET_COLLECTIONS_SUCCED";
export const GET_COLLECTIONS_FAILD = "GET_COLLECTIONS_FAILD";

export const ADD_ALBUM_TO_COLLETION = "ADD_ALBUM_TO_COLLETION";
export const ADD_ALBUM_TO_COLLETION_SUCCED = "ADD_ALBUM_TO_COLLETION_SUCCED";
export const ADD_ALBUM_TO_COLLETION_FAILD = "ADD_ALBUM_TO_COLLETION_FAILD";

export const GET_CLIENT_TOKEN_BRAINTREE = "GET_CLIENT_TOKEN_BRAINTREE";
export const GET_CLIENT_TOKEN_BRAINTREE_SUCCED =
  "GET_CLIENT_TOKEN_BRAINTREE_SUCCESS";
export const GET_CLIENT_TOKEN_BRAINTREE_FAIL =
  "GET_CLIENT_TOKEN_BRAINTREE_FAIL";
